### ISSUE TITLE
Latest `@vercel/node` version causing error

### ISSUE THREAD

**Issue by amyegan** [zeit/now#8513]
### Discussed in https://github.com/vercel/vercel/discussions/8494 Cannot find module 'think-model-mysql'

<div type='discussions-op-text'>

<sup>Originally posted by **lizheming** August 31, 2022</sup>
I have deployed a new app https://waline-test-test.vercel.app/ , it return error give me some tips about 'cant\'t find moudle'. But the module has declared in my dependencies. 

https://github.com/lizheming/waline-test-test

![image](https://user-images.githubusercontent.com/424491/187733729-82d1b01a-6c79-42f4-b36f-388f39faed64.png)

my project depdens module `@waline/vercel` and the missing module `think-model-mysql` has declared in its deps.
![image](https://user-images.githubusercontent.com/424491/187734001-eba4362e-af4c-4a7b-b64c-4c128d2c918f.png)

</div>

---
Backing down to `@vercel/node@2.5.10` works, but getting error with `@vercel/node@2.5.11`, `@vercel/node@2.5.12` and `@vercel/node@2.5.13`.

**Comment by styfle** [comment]
This works with 

It works with the latest `2.5.13` as seen here:

https://github.com/lizheming/waline-test-test/commit/7c470d737f457249636cfee7ed14286e0f7c6d97

https://vercel.com/lizheming/waline-test-test/HhFKvExLxBhfvpGqgvV6PXUYdH4X

https://waline-test-test-52pryxfvl-lizheming.vercel.app

**Comment by styfle** [comment]
I also updated the example repo to use zero config 

- https://github.com/lizheming/waline-test-test/pull/1
