### ISSUE TITLE
cli: `npx ts-eager src` no longer working

### ISSUE THREAD

**Issue by dferber90** [zeit/now#7676]
Scenario: Trying to work on `packages/cli` locally.

The README of `packages/cli` mentions it's possible to run the `cli` using `npx ts-eager src` here https://github.com/vercel/vercel/tree/main/packages/cli#local-development.

This seems to have stopped working. Depending on which command I run, I get a slightly different error.

```
$ npx ts-eager src whoami
Vercel CLI 24.1.1-canary.1 — https://vercel.com/feedback
Error! Cannot find module '/x/vercel/vercel/packages/cli/src/commands/whoami' imported from /x/vercel/vercel/packages/cli/src/index.ts

$ npx ts-eager src init  
Vercel CLI 24.1.1-canary.1 — https://vercel.com/feedback
Error! Directory import '/x/vercel/vercel/packages/cli/src/commands/init' is not supported resolving ES modules imported from /x/vercel/vercel/packages/cli/src/index.ts
```

I guess the different error is due to the respective command either being a directory (`packages/cli/src/commands/init`) or a file (`packages/cli/src/commands/whoami.ts`).

**Comment by dferber90** [comment]
I did a `git bisect` and it seems like a2e4186ccb70c8566667ac4a6aabf99169f6fb7e broke it, which makes sense as it switches from ```const full = require(`./commands/${targetCommand}`).default;``` to `func = await import('./commands/alias');`.

Update for anyone running into this: Running `yarn ts-node src` instead of `yarn ts-eager src` works

A possible solution would be going back to `func = require('./commands/whoami').default;` for all commands in `packages/cli/src/index.ts`. But not sure if that's what we want.
