### ISSUE TITLE
Python runtime does not work on Python 3.12 with ASGI

### ISSUE THREAD

**Issue by kytta** [zeit/now#11545]
Although Python 3.12 is listed as supported by Vercel, it does not work properly with asynchronous functions.

I am trying to deploy a Starlette app (which is ASGI). Just listing Starlette as dependency did not work, as Vercel complained that it's missing `aiohttp`:

```
LAMBDA_WARNING: Unhandled exception. [...]
[ERROR] Runtime.ImportModuleError: Unable to import module 'vc__handler__python': No module named 'aiohttp'
Traceback (most recent call last):
```

So, I've added it to the dependencies (although I don't see the point in it). Nevertheless, it now fails with a different error:

```
LAMBDA_WARNING: Unhandled exception. [...]
[ERROR] TypeError: Queue.__init__() got an unexpected keyword argument 'loop'
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 305, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 202, in __call__
    self.app_queue = asyncio.Queue(loop=loop)
```

I could trace back to this line of `vc_init`:

https://github.com/vercel/vercel/blob/3101d2497f79fd39e927dd9527d0bee800445d28/packages/python/vc_init.py#L202

[According to the Python docs](https://docs.python.org/3/library/asyncio-queue.html#asyncio.Queue), the `loop` argument to the `Queue` was removed in Python 3.10

**Comment by sunnad99** [comment]
I encountered the same issue @kytta 

I, temporarily, solved my issue by downgrading to python 3.9.

https://github.com/orgs/vercel/discussions/6729

**Comment by PaParaZz1** [comment]
> I encountered the same issue @kytta
> 
> I, temporarily, solved my issue by downgrading to python 3.9.
> 
> https://github.com/orgs/vercel/discussions/6729

Could you please provide an example of `vercel.json`? I have changed my settings to py3.9 but it doesn't work (still py3.12).
```json
{
  "builds": [
    {
      "src": "main.py",
      "use": "@vercel/python",
      "config": {
        "legacy": true
      }
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "main.py"
    }
  ]
}
```

**Comment by sunnad99** [comment]
> > I encountered the same issue @kytta
> > I, temporarily, solved my issue by downgrading to python 3.9.
> > https://github.com/orgs/vercel/discussions/6729
> 
> Could you please provide an example of `vercel.json`? I have changed my settings to py3.9 but it doesn't work (still py3.12).
> 
> ```json
> {
>   "builds": [
>     {
>       "src": "main.py",
>       "use": "@vercel/python",
>       "config": {
>         "legacy": true
>       }
>     }
>   ],
>   "routes": [
>     {
>       "src": "/(.*)",
>       "dest": "main.py"
>     }
>   ]
> }
> ```


There is nothing wrong with your config. Also, the config field in the builds object is unnecessary. To tell vercel to pick up the correct version of python, you need to add the "Pipfile" and "Pipfile.lock"

My vercel.json config file looks like:
```
{
  "builds": [
    {
      "src": "app.py",
      "use": "@vercel/python"
    }
  ],
  "routes": [
    {
      "src": "(.*)",
      "dest": "app.py"
    }
  ]
}

```


My pipfile looks like:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
fastapi = "==0.111.0"
requests = "==2.31.0"
beautifulsoup4 = "==4.12.3"
html2text = "==2024.2.26"
validators = "==0.28.1"

[dev-packages]

[requires]
python_version = "3.9"
python_full_version = "3.9.13"
```

Check the following links out for more info:
https://vercel.com/docs/functions/runtimes/python#python-version
https://vercel.com/docs/deployments/build-image/build-image-legacy
https://vercel.com/docs/functions/runtimes/node-js#setting-the-node.js-version-in-project-settings

**Comment by ernests** [comment]
There is a pull request which solves the problem - https://github.com/vercel/vercel/pull/11541

**Comment by sunnad99** [comment]
> There is a pull request which solves the problem - #11541

yes, but while its not live, the solution should be made clear to the users

**Comment by jeremyk** [comment]
I also hit this issue - would really like to avoid downgrading both node and python - any idea when the associated PR will be merged and released?

**Comment by Zapzatron** [comment]
Same problem, waiting for the PR to be accepted

**Comment by adamstoffel** [comment]
+1 FastAPI does not work until this is fixed.

**Comment by kneelesh48** [comment]
Also need to set node version to 18.x in package.json using the code below

```
{
    "engines": {
        "node": "18.x"
    }
}
```

**Comment by sunnad99** [comment]
> I also hit this issue - would really like to avoid downgrading both node and python - any idea when the associated PR will be merged and released?

I would say, switch to flask. Sanic won't work either since its an async framework like FastAPI.

If you can't change the code, I suggest using render.com then because clearly Vercel don't have time for the python community.

> Also need to set node version to 18.x in package.json using the code below
> 
> ```
> {
>     "engines": {
>         "node": "18.x"
>     }
> }
> ```

I actually didn't have to do this, it worked just from changing the setting from the vercel dashboard in the project settings.

**Comment by kytta** [comment]
Closed via https://github.com/vercel/vercel/pull/11675
